### ISSUE TITLE
New recommended method of instantiation in v1.38.0 (backwards-compatible)

### ISSUE THREAD

**Issue by silesky** [segmentio/react-example#20]
In [v1.38.0](https://github.com/segmentio/analytics-next/releases/tag/v1.38.0), we modified the API with the ability to instantiate a buffered analytics method (it's a promise with some additional methods on it) -- it will queue all method calls and flush them once analytics is loaded.

So, instead of: `const [analytics] = await AnalyticsBrowser.load({...` you can do `const analytics = AnalyticsBrowser.load({...`

It's all backwards compatible-- you can still "await" as usual, but that synchronous-style "buffered" instance is going to be our recommended method of instantiation for npm users going forward.

Snippet: 
```ts
import React from 'react'
import { AnalyticsBrowser } from '@segment/analytics-next'

const AnalyticsContext = React.createContext<AnalyticsBrowser>(undefined)

export const AnalyticsProvider: React.FC<{ writeKey: string }> = ({
  children,
  writeKey,
}) => {
  const analytics = React.useMemo(
    () => AnalyticsBrowser.load({ writeKey }), 
    [writeKey]
  )
  return (
    <AnalyticsContext.Provider value={analytics}>
      {children}
    </AnalyticsContext.Provider>
  )
}

// Create an analytics hook that we can use with other components.
export const useAnalytics = () => {
 const result =  React.useContext(AnalyticsContext)
 if (!result) {
   throw new Error('Context used outside of its Provider!')
 }
 return result
}

// use the context we just created...
const TrackButton = () => {
  const analytics = useAnalytics()
  return (
    <button onClick={() => analytics.track('hello world').then(console.log)}>
      Track!
    </button>
  )
}

const App = () => {
  return (
    <AnalyticsProvider writeKey='<YOUR_WRITE_KEY>'>
      <TrackButton />
    </AnalyticsProvider>
  )
```

**Comment by aaronadamsCA** [comment]
This looks like an unfortunate change, because it appears to take away control of when Segment is loaded. At least, I can't find any documentation to describe how this works.

I wish we could simply create a memoized `analytics` that would queue events, and then `useEffect(() => analytics.load())` to initialize Segment after hydration. This would have offered a clean API that mirrors the snippet.

**Comment by silesky** [comment]
@aaronadamsCA that was discussed,

**Comment by silesky** [comment]
@aaronadamsCA that was going to be a breaking change, and we tried not to do that. This reminds me of a similar discussion around the API was using "static methods" on AnalyticsBrowser, but we ended up going a different way because it was conflicting with our goal of supporting multi-instance.

There is no reason to separate instantiation from loading -- If you literally want to mirror the snippet, you can do:

```ts

  window.analytics = React.useMemo(() => {
      return AnalyticsBrowser.load({writeKey})
   }, [writeKey ])
})
```
